### ISSUE TITLE
Pytoch Build with Python3.11 ROCm WSL2 

### ISSUE THREAD

**Issue by unclemusclez** [ROCm/pytorch#1446]
### 🐛 Describe the bug

```bash
In function ‘make_unique’,
    inlined from ‘allocate’ at /home/musclez/ComfyUI/opt/rocm/pytorch/torch/csrc/jit/runtime/static/impl.h:1129:47,
    inlined from ‘__ct ’ at /home/musclez/ComfyUI/opt/rocm/pytorch/torch/csrc/jit/runtime/static/impl.h:1114:41,
    inlined from ‘__ct_base ’ at /home/musclez/ComfyUI/opt/rocm/pytorch/torch/csrc/jit/runtime/static/impl.cpp:2260:7:
/usr/local/include/c++/13.3.1/bits/unique_ptr.h:1085:30: warning: argument 1 value ‘18446744073709551615’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
 1085 |     { return unique_ptr<_Tp>(new remove_extent_t<_Tp>[__num]()); }
      |                              ^
/usr/local/include/c++/13.3.1/new: In member function ‘__ct_base ’:
/usr/local/include/c++/13.3.1/new:128:26: note: in a call to allocation function ‘operator new []’ declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
/usr/bin/ld: /tmp/cciJhomY.ltrans0.ltrans.o: in function `unwind_entry':
<artificial>:(.text+0x7): undefined reference to `unwind_c'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.```

### Error logs

_No response_

### Minified repro

_No response_

### Versions

bug with script?:
```
  File "/home/musclez/collect_env.py", line 1
    404: Not Found
    ^^^
SyntaxError: illegal target for annotatio
```

**Comment by zichguan-amd** [comment]
Hi @unclemusclez, this should have been fixed by PyTorch with b361cd01f1025b13f4980f3b22b05d2324636170.
